name: 🕹 POC - Automatic API Calls

on:
  push:
    branches:
      - main

jobs:
  api-success:
    name: ✅ API Calls - SUCCESS
    runs-on: ubuntu-latest
    outputs:
      details: ${{ steps.run.outputs.details }}

    steps:
      - name: 📥 Code Checkout
        uses: actions/checkout@v5

      - name: 🟢 Node.js Installation
        uses: actions/setup-node@v5
        with:
          node-version: 24

      - name: 📦 Dependencies Installation
        run: npm install

      - name: 🚀 Running Success API Calls
        id: run
        run: node api-calls.js

      - name: 🔍 Debug output SUCCESS
        run: |
          echo "=== GITHUB_OUTPUT ==-"
          cat $GITHUB_OUTPUT

  api-failure:
    name: 🅾️ API Calls - FAILURE
    runs-on: ubuntu-latest
    continue-on-error: true
    outputs:
      details: ${{ steps.run.outputs.details }}

    steps:
      - name: 📥 Code Checkout
        uses: actions/checkout@v5

      - name: 🟢 Node.js Installation
        uses: actions/setup-node@v5
        with:
          node-version: 24

      - name: 📦 Dependencies Installation
        run: npm install

      - name: 💥 Running Failure API Calls
        id: run
        continue-on-error: true
        run: node api-calls-failure.js

      - name: 🔍 Debug output FAILURE
        run: |
          echo "=== GITHUB_OUTPUT ==-"
          cat $GITHUB_OUTPUT

  send-report:
    name: ✉️ Sending Email Report
    runs-on: ubuntu-latest
    needs: [api-success, api-failure]
    if: always()

    steps:
      - name: 📥 Code Checkout
        uses: actions/checkout@v5

      - name: 🟢 Node.js Installation
        uses: actions/setup-node@v5
        with:
          node-version: 24

      - name: 📦 Dependencies Installation
        run: npm install

      - name: 💌 Sending Report with HTML Attachment
        env:
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          REPORT_EMAIL: ${{ secrets.REPORT_EMAIL }}
          WORKFLOW_STATUS: ${{ needs.api-success.result }}
          SUCCESS_DETAILS: ${{ needs.api-success.outputs.details }}
          FAILURE_DETAILS: ${{ needs.api-failure.outputs.details }}
          RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        run: |
          echo "=== DEBUG SUCCESS_DETAILS ==="
          echo "$SUCCESS_DETAILS"
          echo "=== DEBUG FAILURE_DETAILS ==="
          echo "$FAILURE_DETAILS"
          node send-report.js
